#! /usr/bin/env bash

changedir() {
  echo "Building plugin $@"
  pushd $@ >> /dev/null
}

die() {
  echo "Failure: $@"
  exit 1
}

pushd "plugins" >> /dev/null
  for D in `find . -mindepth 1 -maxdepth 1 -type d | grep -v core | grep -v shared`
  do
    changedir $D
      go get -d || die "Could not fetch dependencies for example: $D"
      go install || die "Could not build example: $D"
    popd >> /dev/null
  done
popd >> /dev/null
